GET http://localhost:3001/api/persons/
###

DELETE http://localhost:3001/api/persons/65886748561a9bd76d00ad76
###

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
 "name":"Sa",
 "number":"123"
}
###

PUT http://localhost:3001/api/persons/65886bd9cc6556d98f0141af
Content-Type: application/json

{
    "name":"Sharmila",
    "number":"321"
}