
GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs/
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2NWFlNDI0OTQyMTI0Yzc3MjM2OTljYjgiLCJpYXQiOjE3MDU5MTkwNzEsImV4cCI6MTcwNTkyMjY3MX0.gUv77vj5zU00_bxyQvyydZ1GUg9Ugx4i6w5EpLxSEMA

{
    "title":"The Joel Test: 12 Steps to Better Code",
    "author":"Joel Spolsky",
    "userId":"6599a0e1cc09568ab6b146a4",
    "url":"https://www.joelonsoftware.com/2000/08/09/the-joel-test-12-steps-to-better-code/",
    "likes":0
}
###

PUT http://localhost:3003/api/blogs/65ae42ef42124c7723699cbf
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2NWFlNDI0OTQyMTI0Yzc3MjM2OTljYjgiLCJpYXQiOjE3MDU5ODkyNzUsImV4cCI6MTcwNTk5Mjg3NX0.tCH5n0v78i0v7NPmqC2Ft_EzjrYCw6K-tspPnewhUZo._6TjpDwVFpzMmMS4e8Qd42t0hRDZp1mWy411o9SJoLk

{
    "title":"The Joel Test: 12 Steps to Better Code",
    "author":"Joel Spolsky",
    "url":"https://www.joelonsoftware.com/2000/08/09/the-joel-test-12-steps-to-better-code/",
    "likes":100
}
###

# DELETE  http://localhost:3003/api/blogs/659530c9fcf25973903f8e7d
###

DELETE  http://localhost:3003/api/blogs/65a9f248abdc938a9971024d
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlVzZXIxIiwiaWQiOiI2NTliODU4MTUyOTIzOWMzMDQ0M2FlNGUiLCJpYXQiOjE3MDU2NTM0OTIsImV4cCI6MTcwNTY1NzA5Mn0.dqaLLsXA5H4ZasZxS9yjFKAb-3p1Dn4M_qMBTvrgOTM

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username":"mluukkai",
    "name":"Matti Luukkainen",
    "password":"123456"
}

###

POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username":"mluukkai",
    "password":"123456"
}


